server:
  port: 8000
  servlet:
    context-path: /users

management:
  health:
    livenessState.enabled: true
    readinessState.enabled: true
  endpoint.health.probes.enabled: true

spring:
  application.name: service-users
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bmp_test?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: password
    initialization-mode: always
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: false
      hibernate:
        ddl-auto: create
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  cloud:
    stream:
      binder:
        brokers: localhost:9092
  zipkin:
    baseUrl: http://127.0.0.1:9411/


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

